services:
  postgres:
    image: postgres:15-alpine
    container_name: movie_postgres
    environment:
      POSTGRES_DB: movie_db
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: pgpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: